# Generated by Django 5.0.1 on 2024-01-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_summary_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
    ]
